version: '3.8'
services:
  postgres-database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    driver: local