spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: shopping-list-api
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view : false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG

spring.h2.console.enabled: true
spring.h2.console.path: /h2