spring:
  profiles:
    active: local
  application:
    name: shopping-list-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    open-in-view : false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG